/* ================= CAN ID Macros ================= */

#define CAN_ID_BPS_STATUS 0x1
#define CAN_ID_BPS_VOLTAGE_ARR_0 0x2
#define CAN_ID_BPS_VOLTAGE_ARR_1 0x3
#define CAN_ID_BPS_VOLTAGE_ARR_2 0x4
#define CAN_ID_BPS_VOLTAGE_ARR_3 0x5
#define CAN_ID_BPS_VOLTAGE_ARR_4 0x6
#define CAN_ID_BPS_VOLTAGE_ARR_5 0x7
#define CAN_ID_BPS_VOLTAGE_ARR_6 0x8
#define CAN_ID_BPS_VOLTAGE_ARR_7 0x9
#define CAN_ID_BPS_PACK_CURRENT 0xA
#define CAN_ID_BPS_TEMPERATURE_ARR_0 0x10
#define CAN_ID_BPS_TEMPERATURE_ARR_1 0x11
#define CAN_ID_BPS_TEMPERATURE_ARR_2 0x12
#define CAN_ID_BPS_TEMPERATURE_ARR_3 0x13
#define CAN_ID_BPS_TEMPERATURE_ARR_4 0x14
#define CAN_ID_BPS_TEMPERATURE_ARR_5 0x15
#define CAN_ID_BPS_TEMPERATURE_ARR_6 0x16
#define CAN_ID_BPS_TEMPERATURE_ARR_7 0x17
#define CAN_ID_BPS_PRECHARGE_VOLTAGES 0x20

/* ================= CAN Length Macros ================= */

#define CAN_DLC_BPS_STATUS 7
#define CAN_DLC_BPS_VOLTAGE_ARR_0 4
#define CAN_DLC_BPS_VOLTAGE_ARR_1 4
#define CAN_DLC_BPS_VOLTAGE_ARR_2 4
#define CAN_DLC_BPS_VOLTAGE_ARR_3 4
#define CAN_DLC_BPS_VOLTAGE_ARR_4 4
#define CAN_DLC_BPS_VOLTAGE_ARR_5 4
#define CAN_DLC_BPS_VOLTAGE_ARR_6 4
#define CAN_DLC_BPS_VOLTAGE_ARR_7 4
#define CAN_DLC_BPS_PACK_CURRENT 5
#define CAN_DLC_BPS_TEMPERATURE_ARR_0 7
#define CAN_DLC_BPS_TEMPERATURE_ARR_1 7
#define CAN_DLC_BPS_TEMPERATURE_ARR_2 7
#define CAN_DLC_BPS_TEMPERATURE_ARR_3 7
#define CAN_DLC_BPS_TEMPERATURE_ARR_4 7
#define CAN_DLC_BPS_TEMPERATURE_ARR_5 7
#define CAN_DLC_BPS_TEMPERATURE_ARR_6 7
#define CAN_DLC_BPS_TEMPERATURE_ARR_7 7
#define CAN_DLC_BPS_PRECHARGE_VOLTAGES 6

// CAN_RECV_ENTRY(ID, SIZE, CIRCULAR)

CAN_RECV_ENTRY(CAN_ID_BPS_STATUS, CAN_DLC_BPS_STATUS, true)
CAN_RECV_ENTRY(CAN_ID_BPS_VOLTAGE_ARR_0, CAN_DLC_BPS_VOLTAGE_ARR_0, true)
CAN_RECV_ENTRY(CAN_ID_BPS_VOLTAGE_ARR_1, CAN_DLC_BPS_VOLTAGE_ARR_1, true)
CAN_RECV_ENTRY(CAN_ID_BPS_VOLTAGE_ARR_2, CAN_DLC_BPS_VOLTAGE_ARR_2, true)
CAN_RECV_ENTRY(CAN_ID_BPS_VOLTAGE_ARR_3, CAN_DLC_BPS_VOLTAGE_ARR_3, true)
CAN_RECV_ENTRY(CAN_ID_BPS_VOLTAGE_ARR_4, CAN_DLC_BPS_VOLTAGE_ARR_4, true)
CAN_RECV_ENTRY(CAN_ID_BPS_VOLTAGE_ARR_5, CAN_DLC_BPS_VOLTAGE_ARR_5, true)
CAN_RECV_ENTRY(CAN_ID_BPS_VOLTAGE_ARR_6, CAN_DLC_BPS_VOLTAGE_ARR_6, true)
CAN_RECV_ENTRY(CAN_ID_BPS_VOLTAGE_ARR_7, CAN_DLC_BPS_VOLTAGE_ARR_7, true)
CAN_RECV_ENTRY(CAN_ID_BPS_PACK_CURRENT, CAN_DLC_BPS_PACK_CURRENT, true)
CAN_RECV_ENTRY(CAN_ID_BPS_TEMPERATURE_ARR_0, CAN_DLC_BPS_TEMPERATURE_ARR_0, true)
CAN_RECV_ENTRY(CAN_ID_BPS_TEMPERATURE_ARR_1, CAN_DLC_BPS_TEMPERATURE_ARR_1, true)
CAN_RECV_ENTRY(CAN_ID_BPS_TEMPERATURE_ARR_2, CAN_DLC_BPS_TEMPERATURE_ARR_2, true)
CAN_RECV_ENTRY(CAN_ID_BPS_TEMPERATURE_ARR_3, CAN_DLC_BPS_TEMPERATURE_ARR_3, true)
CAN_RECV_ENTRY(CAN_ID_BPS_TEMPERATURE_ARR_4, CAN_DLC_BPS_TEMPERATURE_ARR_4, true)
CAN_RECV_ENTRY(CAN_ID_BPS_TEMPERATURE_ARR_5, CAN_DLC_BPS_TEMPERATURE_ARR_5, true)
CAN_RECV_ENTRY(CAN_ID_BPS_TEMPERATURE_ARR_6, CAN_DLC_BPS_TEMPERATURE_ARR_6, true)
CAN_RECV_ENTRY(CAN_ID_BPS_TEMPERATURE_ARR_7, CAN_DLC_BPS_TEMPERATURE_ARR_7, true)
CAN_RECV_ENTRY(CAN_ID_BPS_PRECHARGE_VOLTAGES, CAN_DLC_BPS_PRECHARGE_VOLTAGES, true)