#include "CarCAN_can_msgs.h"
#include "BPSCAN_can_msgs.h"

CAN_RECV_ENTRY(CAN_ID_DRIVER_INPUT_STATUS, CAN_DLC_DRIVER_INPUT_STATUS, true)
CAN_RECV_ENTRY(CAN_ID_CHARGER_INTERFACE_STATUS, CAN_DLC_CHARGER_INTERFACE_STATUS, true)
