#define PLACEHOLDERPIN GPIO_PIN_1
#define PLACEHOLDERPIN2 GPIO_PIN_2
#define PLACEHOLDERPIN3 GPIO_PIN_3
#define PLACEHOLDERPIN4 GPIO_PIN_4
#define PLACEHOLDERPORT GPIOA
#define PLACEHOLDER_IRQn EXTI0_IRQn


// CONTACTOR PINDEF
#define HV_POSITIVE_CONTROL_PIN_NUM PLACEHOLDERPIN
#define HV_POSITIVE_CONTROL_PORT PLACEHOLDERPORT
#define HV_POSITIVE_SENSE_PIN_NUM PLACEHOLDERPIN
#define HV_POSITIVE_SENSE_PORT PLACEHOLDERPORT

#define HV_NEGATIVE_CONTROL_PIN_NUM PLACEHOLDERPIN
#define HV_NEGATIVE_CONTROL_PORT PLACEHOLDERPORT
#define HV_NEGATIVE_SENSE_PIN_NUM PLACEHOLDERPIN2
#define HV_NEGATIVE_SENSE_PORT PLACEHOLDERPORT

#define ARRAY_CONTROL_PIN_NUM PLACEHOLDERPIN
#define ARRAY_CONTROL_PORT PLACEHOLDERPORT
#define ARRAY_SENSE_PIN_NUM PLACEHOLDERPIN3
#define ARRAY_SENSE_PORT PLACEHOLDERPORT

#define ARRAY_PRE_CONTROL_PIN_NUM PLACEHOLDERPIN
#define ARRAY_PRE_CONTROL_PORT PLACEHOLDERPORT
#define ARRAY_PRE_SENSE_PIN_NUM PLACEHOLDERPIN4
#define ARRAY_PRE_SENSE_PORT PLACEHOLDERPORT

// Status LED Shift-Reg PINDEF
#define LED_SRCLK_PIN_NUM PLACEHOLDERPIN
#define LED_SRCLK_PORT PLACEHOLDERPORT
#define LED_SER_PIN_NUM PLACEHOLDERPIN
#define LED_SER_PORT PLACEHOLDERPORT
#define LED_RCLK_PIN_NUM PLACEHOLDERPIN
#define LED_RCLK_PORT PLACEHOLDERPORT

// EXIt
#define HV_POSTIVE_SENSE_EXTI PLACEHOLDER_IRQn
#define HV_NEGATIVE_SENSE_EXTI PLACEHOLDER_IRQn
#define ARRAY_SENSE_EXTI PLACEHOLDER_IRQn
#define ARRAY_PRE_SENSE_EXTI PLACEHOLDER_IRQn


