#define PLACEHOLDERPIN GPIO_PIN_4
#define PLACEHOLDERPORT GPIOA


// CONTACTOR PINDEF
#define HV_POSITIVE_CONTROL_PIN_NUM PLACEHOLDERPIN
#define HV_POSITIVE_CONTROL_PORT PLACEHOLDERPORT
#define HV_POSITIVE_SENSE_PIN_NUM PLACEHOLDERPIN
#define HV_POSITIVE_SENSE_PORT PLACEHOLDERPORT

#define HV_NEGATIVE_CONTROL_PIN_NUM PLACEHOLDERPIN
#define HV_NEGATIVE_CONTROL_PORT PLACEHOLDERPORT
#define HV_NEGATIVE_SENSE_PIN_NUM PLACEHOLDERPIN
#define HV_NEGATIVE_SENSE_PORT PLACEHOLDERPORT

#define ARRAY_CONTROL_PIN_NUM PLACEHOLDERPIN
#define ARRAY_CONTROL_PORT PLACEHOLDERPORT
#define ARRAY_SENSE_PIN_NUM PLACEHOLDERPIN
#define ARRAY_SENSE_PORT PLACEHOLDERPORT

#define ARRAY_PRE_CONTROL_PIN_NUM PLACEHOLDERPIN
#define ARRAY_PRE_CONTROL_PORT PLACEHOLDERPORT
#define ARRAY_PRE_SENSE_PIN_NUM PLACEHOLDERPIN  
#define ARRAY_PRE_SENSE_PORT PLACEHOLDERPORT

// Status LED Shift-Reg PINDEF
#define LED_SRCLK_PIN_NUM PLACEHOLDERPIN
#define LED_SRCLK_PORT PLACEHOLDERPORT
#define LED_SER_PIN_NUM PLACEHOLDERPIN
#define LED_SER_PORT PLACEHOLDERPORT
#define LED_RCLK_PIN_NUM PLACEHOLDERPIN
#define LED_RCLK_PORT PLACEHOLDERPORT
