#define PLACEHOLDERPIN GPIO_PIN_1
#define PLACEHOLDERPORT GPIOA

// CONTACTOR PINDEF
#define HV_PLUS_CONTROL_PIN_NUM PLACEHOLDERPIN 
#define HV_PLUS_CONTROL_PORT PLACEHOLDERPORT
#define HV_PLUS_SENSE_PIN_NUM PLACEHOLDERPIN
#define HV_PLUS_SENSE_PORT PLACEHOLDERPORT

#define HV_MINUS_CONTROL_PIN_NUM PLACEHOLDERPIN
#define HV_MINUS_CONTROL_PORT PLACEHOLDERPORT
#define HV_MINUS_SENSE_PIN_NUM PLACEHOLDERPIN
#define HV_MINUS_SENSE_PORT PLACEHOLDERPORT

#define ARRAY_CONTROL_PIN_NUM PLACEHOLDERPIN
#define ARRAY_CONTROL_PORT PLACEHOLDERPORT
#define ARRAY_SENSE_PIN_NUM PLACEHOLDERPIN
#define ARRAY_SENSE_PORT PLACEHOLDERPORT

#define ARRAY_PRE_CONTROL_PIN_NUM PLACEHOLDERPIN
#define ARRAY_PRE_CONTROL_PORT PLACEHOLDERPORT
#define ARRAY_PRE_SENSE_PIN_NUM PLACEHOLDERPIN
#define ARRAY_PRE_SENSE_PORT PLACEHOLDERPORT

// Status LED Shift-Reg PINDEF
#define LED_SRCLK_PIN_NUM GPIO_PIN_14 
#define LED_SRCLK_PORT GPIOB
#define LED_SER_PIN_NUM GPIO_PIN_9  
#define LED_SER_PORT GPIOB
#define LED_RCLK_PIN_NUM GPIO_PIN_15 
#define LED_RCLK_PORT GPIOB



